[workspace]
members = [
  "bench/runners/min-html-onepass",
  "bench/runners/min-html",
  "debug/diff/c14n",
  "debug/diff/charlines",
  "minhtml",
  "min-html-common",
  "min-html-java",
  "min-html-nodejs",
  "min-html-onepass-python",
  "min-html-onepass",
  "min-html-python",
  "min-html-ruby/ext/min_html",
  "min-html-wasm",
  "min-html",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
strip = true

[profile.release.package."*"]
codegen-units = 1
opt-level = 3
