#!/usr/bin/env bash

set -Eeuxo pipefail

pushd "$(dirname "$0")" >/dev/null

target="${TARGET:-bundler}"

# getrandom 0.3 requires this cfg flag to build for wasm32-unknown-unknown.
export RUSTFLAGS='--cfg getrandom_backend="wasm_js"'

rm -rf pkg
wasm-pack build --target "$target"
pushd pkg
# `bundler` is for WASM/npm, `deno` is for Deno.
if [[ "$target" = "bundler" ]]; then
  jq -s '.[0] * .[1]' package.json ../package.merge.json > package.new.json
  mv package.new.json package.json
  rm .gitignore
  # https://developers.cloudflare.com/workers/languages/rust/#javascript-plumbing-wasm-bindgen
  cp ../index.cloudflare.js index.js
elif [[ "$target" = "deno" ]]; then
  rm .gitignore
  cp ../deno.json .
  # Necessary for Deno.
  sed -i '1s%^%/* @ts-self-types="./index.d.ts" */\n%' index.js
elif [[ "$target" = "web" ]]; then
  rm package.json .gitignore
fi
popd

popd >/dev/null
