[package]
name = "min-html-bench"
publish = false
version = "0.0.1"
authors = ["QQSHI13"]
edition = "2018"

[dependencies]
min-html = { path = "../../../min-html" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["lightningcss"]
lightningcss = ["min-html/lightningcss"]
