name: Build and publish Deno package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # https://jsr.io/docs/publishing-packages#publishing-from-github-actions
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v7

      - name: Get version
        id: version
        shell: bash
        run: echo "VERSION=$([[ "$GITHUB_REF" == refs/tags/v* ]] && echo ${GITHUB_REF#refs/tags/v} || echo '0.0.0')" >> "$GITHUB_OUTPUT"

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Build native module
        working-directory: ./min-html-wasm
        shell: bash
        run: TARGET=deno ./build

      - name: Publish to JSR
        working-directory: ./min-html-wasm
        if: "${{ steps.version.outputs.VERSION != '0.0.0' }}"
        shell: bash
        run: |
          version="${{ steps.version.outputs.VERSION }}"
          if curl -sf "https://jsr.io/@minhtml/deno/${version}" >/dev/null; then
            echo "JSR version ${version} already exists, skipping publish."
            exit 0
          fi
          # Sadly `jsr` ignores .gitignore files (i.e. our built dist package) and will fail on a dirty repo,
          # contrary to almost every other build/package system.
          # Therefore, we first move to a non-ignored folder.
          mv -iv pkg pkg-pub
          cd pkg-pub
          npx jsr publish --allow-dirty
